name: Test package quality

on: push

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Ensure submodules are checked out

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Install Eigen
      run: sudo apt-get install libeigen3-dev

    - name: Install package
      run: |
        pip install -e .  # Install your package in editable mode

    - name: Install submodule package
      run: |
        pip install ./trajectories/trajectory_generation  # Adjust this path as necessary

    - name: Unit tests
      run: |
        python -m pytest tests/
        rm -rf tmp/
